[features]
seeds = false
skip-lint = false
[programs.localnet]
fluxus = "4XvNtZ1Z9GZ5YyZDJaAxC5TSFGHx1McbL5G2YphGQ1EG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/saicharanpogul/Desktop/WBA/fluxus/fluxus.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR"

[[test.validator.clone]]
address = "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g"