[features]
seeds = false
skip-lint = false
[programs.localnet]
fluxus = "GYdBrTgUFvAfdgYVNK3bUudrMoaFQ6CjvRCaA7SMfMj8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/saicharanpogul/Desktop/WBA/fluxus/fluxus.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
